### ISSUE TITLE
Broken link on wiki-page

### ISSUE THREAD

**Issue by jorander** [AvanzaBank/astrix#10]
The link https://github.com/AvanzaBank/astrix/wiki/part3.md at the bottom of page https://github.com/AvanzaBank/astrix/wiki/Service-Discovery-and-Service-Binding seems to be broken. When clicked the browser is sent back to https://github.com/AvanzaBank/astrix/wiki.

Best Regards
Jörgen

**Comment by eliaslindholm** [comment]
Hi Jörgen!

Thanks for your feedback! I'm afraid there is no part three yet:( There was a draft for part three before we moved the project from our internal gitlab server to github, but I removed the draft during the migration but forgot to remove the link.

I guess its time to put some effort into the documentation. I will write an entry for part three, and use this ticket to document progress. 

Please feel free to use this ticket to request documentation on other parts of the framework as well!

/Elias
